spring:
  application:
    name: HabitTracker-Backend


  datasource:
    url: jdbc:mariadb://localhost:3306/habits?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver


  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    default-schema: habits
    drop-first: false


  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false


info:
  app:
    version: 1.0.0

security:
  jwt:
    secret-key: 7Fg7EkwxLeOO3GRLc3IYFwBUiqlHZPfJadIHF8m6ZbE=
    # 1h in millisecond
    expiration-time: 3600000