name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Run tests
        run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent clean package -P qodana-report
#        working-directory: .qodana/code-coverage

      - name: Archive coverage data # Archive data for using by Qodana
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-tests
          path: .qodana/code-coverage

      - name: Qodana Scan # Run Qodana
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_JS }}
        with:
          args: "-i,JS/jest,--linter,jetbrains/qodana-js:2024.1"
          pr-mode: false
#jobs:
#  qodana:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#      pull-requests: write
#      checks: write
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
#          fetch-depth: 0  # a full history is required for pull request analysis
#      - name: 'Qodana Scan'
#        uses: JetBrains/qodana-action@v2024.1
#        env:
#          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}