name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - master # The 'main' branch
      - 'releases/*' # The release branches

jobs:
  build:

    runs-on: ubuntu-latest


    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Validate Maven Wrapper
        run: mvn --version
#        working-directory: JVM/jacoco/maven

      - name: Run tests
        run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent clean package -P qodana-report
#        working-directory: JVM/jacoco/maven


      - name: Archive coverage data
        uses: actions/upload-artifact@v2
        with:
          name: maven-coverage-data-jacoco
          path: .qodana/code-coverage

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
#        run: qodana scan -e QODANA_TOKEN=${{ secrets.QODANA_TOKEN_MVN_JACOCO }} -l jetbrains/qodana-jvm:2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: "-e,QODANA_TOKEN=-${{ secrets.QODANA_TOKEN }},-l,jetbrains/qodana-jvm:2024.1"
          pr-mode: false
#jobs:
#  qodana:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#      pull-requests: write
#      checks: write
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
#          fetch-depth: 0  # a full history is required for pull request analysis
#      - name: 'Qodana Scan'
#        uses: JetBrains/qodana-action@v2024.1
#        env:
#          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}